%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nolanreis/GitHub/ecs171project/n_data/Baseball_hitters_data.xlsx
%    Worksheet: editted
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/13 10:56:32

%% Import the data
[~, ~, raw] = xlsread('/Users/nolanreis/GitHub/ecs171project/n_data/Baseball_hitters_data.xlsx','editted');
raw = raw(2:end,2:end);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Exclude rows with non-numeric cells
I = ~all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2); % Find rows with non-numeric cells
raw(I,:) = [];

%% Create output variable
Baseballhittersdata = reshape([raw{:}],size(raw));
X = Baseballhittersdata(:,1:end-1);
Y = Baseballhittersdata(:,end);

%normalize stats
X(:,1) =  Baseballhittersdata(:,1)/max(Baseballhittersdata(:,1));
for i = 5:9
    X(:,i) =  Baseballhittersdata(:,i)/max(Baseballhittersdata(:,i));
end

X(:,end) =  Baseballhittersdata(:,end-1)/max(Baseballhittersdata(:,end-1));
%% Clear temporary variables
clearvars raw I;